### ISSUE TITLE
"invalid message format" error when string to write contains a NUL character

### ISSUE THREAD

**Issue by almacha** [Suor/sql-bricks-postgres#10]
When I send a string with a \0 in it, I get an "invalid message format" error.

```
var sql = require('sql-bricks-postgres');

// pool is the "pool" object provided by module pg 6.1.0
pool.connect(function(error, client, done) {
  if (error) return console.error(error.stack);

  client.query(sql.insertInto('test', 's').values('test\0').toString(), function(error, result) {
    if (error) return console.error(error.stack);
  });
});
```

I get:

> error: invalid message format
>     at Connection.parseE (/Users/raphaelchampeimont/nodejs-doctrine/node_modules/pg/lib/connection.js:554:11)
>     at Connection.parseMessage (/Users/raphaelchampeimont/nodejs-doctrine/node_modules/pg/lib/connection.js:381:17)
>     at TLSSocket.<anonymous> (/Users/raphaelchampeimont/nodejs-doctrine/node_modules/pg/lib/connection.js:117:22)
>     at emitOne (events.js:77:13)
>     at TLSSocket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:153:18)
>     at TLSSocket.Readable.push (_stream_readable.js:111:10)
>     at TLSWrap.onread (net.js:536:20)
> 

I am using sql-bricks-postgres@0.4.2

**Comment by Suor** [comment]
You should never use `.toString()` when making actual query, use `.toParams()`. You might also want to look at [pg-bricks](https://github.com/Suor/pg-bricks):

```js
var db = require('pg-bricks').configure(process.env.DATABASE_URL);

db.insertInto('test', 's').values('test\0').run(callback);
```

The syntax for making queries is the same, but you get `.run()` and other executors.

**Comment by almacha** [comment]
OK thank you. I now get "invalid byte sequence for encoding "UTF8": 0x00" but I guess this is an "expected" error now.
