### ISSUE TITLE
Binary is a reserved word in Postgres and so maybe others

### ISSUE THREAD

**Issue by christiaanwesterbeek** [Suor/sql-bricks-postgres#13]
In contrast to the reserved words in sql-bricks https://github.com/CSNW/sql-bricks/blob/master/sql-bricks.js#L1001, I think sql-bricks-postgres needs a variant to that list.

For example, this:

```javascript
const update = require('sql-bricks-postgres').update
const { text, values } = update('data.file', {binary: <Buffer 49 44 ... >}).where('id', 1).toParams()

// text --> UPDATE data.file SET binary = $1 WHERE id = $2
// values: [  <Buffer 49 44 ... >, 1 ]
await pg_client.query(text, values)
```
Fails with this error:
> syntax error at or near "binary"

Or should I direct this issue at sql-bricks?

**Comment by Suor** [comment]
Looked at it. This is both sql-bricks and sql-bricks-postgres issue because autoquoting is non-overridable now. Once that's fixed in sql-bricks I can add new reserved keyword. 

Opened an issue on sql-bricks.

**Comment by Suor** [comment]
Master should work now.
