### ISSUE TITLE
Update `noWait` for postgres

### ISSUE THREAD

**Issue by joelmukuthu** [Suor/sql-bricks-postgres#15]
With sql-bricks, `noWait` builds SQL such as:

```sql
select('addr_id').from('person').forUpdate().of('addr_id').noWait();
// SELECT addr_id FROM person FOR UPDATE OF addr_id NO WAIT
```

For postgres though, `NO WAIT` should be `NOWAIT`. Is it possible to make this change in this module?

**Comment by Suor** [comment]
Hmm, this is implemented in sql-bricks and I can't see why it's implemented this way. You can create an issue there.

**Comment by joelmukuthu** [comment]
Oh right. I just assumed other databases have it as `NO WAIT`. Will create an issue there
