### ISSUE TITLE
Range operators and functions

### ISSUE THREAD

**Issue by sandfox** [Suor/sql-bricks-postgres#2]
I'd like to use some range queries such as 

``` sql
SELECT *
FROM   time_limits
WHERE  name = 'lucy`
AND    tsrange(start_date_time, end_date_time, '[]')
    @> tsrange('2010-08-08 00:00', '2010-08-08 00:05', '[]')
```

As per this bit of the postgres manual http://www.postgresql.org/docs/9.2/static/functions-range.html

I can't work out a way to do this with postgres-bricks (I might be aiming at the wrong place here and maybe this issue should be in the sql-bricks module but I think it's postgres specific right now).

Is there a simple way to hack this in without an update to sql-brick-postgres ?

**Comment by Suor** [comment]
The better way could be provided via https://github.com/CSNW/sql-bricks/issues/74
