### ISSUE TITLE
Composite "WHERE IN" Support

### ISSUE THREAD

**Issue by nickschwab** [Suor/sql-bricks-postgres#6]
Support for composite "IN" conditions where two or more fields are specified along with a multidimensional array or array of objects.

e.g.

sql.in("(col1,col2)", [[1,2],[3,4]]);

Currently invalid example result:
SELECT * FROM beacons WHERE (major, minor) IN ('64404,20884','47805,16497')

Expected example result:
SELECT * FROM beacons WHERE (major, minor) IN (('64404','20884'),('47805','16497'))

Current work-around (after validating the multidimensional array):
sql.in("(major, minor)", sql(myMultidimensionalArray.map(function(pair, index) {return '(' + pair[0] + ',' + pair[1] + ')';}).join(',')))

See also:
http://stackoverflow.com/questions/6672665/doing-a-where-in-on-multiple-columns-in-postgresql

Originated on Twitter: https://twitter.com/nickschwab/status/629024436532944896
Moved to sql-bricks-postgres after deliberation in sql-bricks: https://github.com/CSNW/sql-bricks/issues/72#issuecomment-130732395

**Comment by Suor** [comment]
Can you create a failing test for this?

**Comment by nickschwab** [comment]
sql.select()
.from("table")
.where(
sql.in("(column1, column2)", [["64404","20884"],["47805","16497"]])
);


The above successfully generates a query, but it concatenates each sub-array into a single string which produces an incorrect query.

**Comment by Suor** [comment]
I looked through postgresql docs and looks like it doesn't suport this.

**Comment by Suor** [comment]
You can try joining with values tables:
```js
sql.select().from('some_table')
   .join(sql.values([{a:1, b:2}, {a:1, b:3}]).columns().as('v'), 
         {a: 'some_table.a', b: 'some_table.b'})
```
