### ISSUE TITLE
array update/inserts malformed

### ISSUE THREAD

**Issue by nbrustein** [Suor/sql-bricks-postgres#7]
I'm not sure if this is an issue in sql-bricks or an issue in sql-bricks-postgres, so I'm creating issues in both projects.

When I try to insert (or update) into an array column of type uuid[], then value is malformed.  There should be quotes around it, but there are not. 

sql-bricks generates this:

     INSERT INTO my_table (empty_array, array_with_something) VALUES ({}, {'aee828d5-6615-4fbd-bc58-41ccd39470ae'})

but should generate

     INSERT INTO my_table (empty_array, array_with_something) VALUES ('{}','{\'aee828d5-6615-4fbd-bc58-41ccd39470ae\'}')

I am able to get the query to work with the following regex, though this would not work in all cases:

        sql = sql.replace(/(\{)([^\}]*)(\})/g, function(ignore1, ignore2, content) {
            return '\'{' + content.replace(/\'/g, '"') + '}\'';
        });

**Comment by Suor** [comment]
Post code please.

**Comment by nbrustein** [comment]
I used this command ...

        CREATE TABLE array_test(vals text[]);

... to create this table ...

	  Table "public.array_test"
	 Column |  Type  | Modifiers
	--------+--------+-----------
	 vals   | text[] |

... And then this code ...

        var sqlBricks = require('sql-bricks-postgres');

        sqlBricks.insertInto('array_test')
        .values({
            vals: ['a', 'b', 'c']
        })
        .toString()

... generates this query ...

        INSERT INTO array_test (vals) VALUES ({'a', 'b', 'c'})

... resulting in this error from postgres ...

        error: syntax error at or near "{"

I think that the desired query is ...

        INSERT INTO array_test (vals) VALUES ('{"a", "b", "c"}');

... or at least that one works to insert the row

**Comment by nbrustein** [comment]
prust from the sql-bricks project believes that this is an issue in sql-bricks-postgres, not in sql-bricks.

https://github.com/CSNW/sql-bricks/issues/78#event-490145617

**Comment by AndyMathys** [comment]
@Suor : did you see this issue on sql-bricks?
https://github.com/CSNW/sql-bricks/issues/81
